name: protopipe-CTADIRAC-dev
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.8
  - pip
  # GRID
  - dirac-grid
  - diracgrid::fts3
  - gfal2=2.20.2 # needed to avoid ECOMM on macos bug
  - voms
  # other required dependencies
  - tqdm
  - pytables
  - pyyaml
  # Testing
  - pytest
  - codecov
  - pytest-cov
  - pip:
      - CTADIRAC
