name: protopipe-CTADIRAC
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  # GRID
  - dirac-grid
  - diracgrid::fts3
  - gfal2=2.20.2 # needed to avoid ECOMM on macos bug
  - voms
  # Other required dependencies
  - pytables
  - pyyaml
  - tqdm
  - pip:
      - protopipe
      - CTADIRAC
