name: Publish Docker image for latest release

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image for released version to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/protopipe-ctadirac

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./containers/Docker/Development
          file: ./containers/Docker/Release/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
